#!/bin/bash
# Builds paperMD in release mode and assembles a signed dist/paperMD.app bundle.
# Requires only Command Line Tools — no Xcode.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/dist/paperMD.app"
VERSION="${PAPERMD_VERSION:-1.0.0}"

echo "==> swift build -c release"
cd "$ROOT"
swift build -c release

BIN="$ROOT/.build/release/paperMD"
RESOURCE_BUNDLE="$ROOT/.build/release/paperMD_paperMD.bundle"

echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN" "$APP/Contents/MacOS/paperMD"
# Bundle.module looks for this inside the main bundle's Resources dir.
cp -R "$RESOURCE_BUNDLE" "$APP/Contents/Resources/"

# Optional icon (generated by Scripts/make-icon.swift in a later task).
ICON_KEY=""
if [[ -f "$ROOT/Scripts/paperMD.icns" ]]; then
    cp "$ROOT/Scripts/paperMD.icns" "$APP/Contents/Resources/paperMD.icns"
    ICON_KEY="<key>CFBundleIconFile</key><string>paperMD</string>"
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>paperMD</string>
    <key>CFBundleIdentifier</key><string>com.washi.papermd</string>
    <key>CFBundleName</key><string>paperMD</string>
    <key>CFBundleDisplayName</key><string>paperMD</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundleVersion</key><string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key><string>15.0</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSPrincipalClass</key><string>NSApplication</string>
    <key>NSSupportsAutomaticTermination</key><false/>
    ${ICON_KEY}
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key><string>Markdown Document</string>
        <key>CFBundleTypeRole</key><string>Editor</string>
        <key>LSHandlerRank</key><string>Owner</string>
        <key>LSItemContentTypes</key>
        <array><string>net.daringfireball.markdown</string></array>
        <key>CFBundleTypeExtensions</key>
        <array><string>md</string><string>markdown</string></array>
      </dict>
    </array>
</dict>
</plist>
PLIST

echo "==> Codesigning (ad-hoc)"
codesign --force --sign - "$APP"

echo ""
echo "Done: $APP"
echo "Run it:      open '$APP'"
echo "Install it:  cp -R '$APP' /Applications/"
